[package]
name = "voteme"
version = "0.1.0"
edition = "2024"

[lib] 
crate-type = ["cdylib"]

[dependencies]
pumpkin-plugin-api = { git = "https://github.com/Pumpkin-MC/Pumpkin", tag = "0.2.0+26.3-26.51" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rsa = { version = "0.9", features = ["sha2"] }
pkcs1 = { version = "0.7", features = ["pem"] }
pkcs8 = { version = "0.10", features = ["pem"] }
hmac = "0.12"
sha2 = "0.10"
subtle = "2.6"
base64 = "0.22"
rand = "0.8"
thiserror = "2.0"
libc = "0.2"

[profile.release] 
lto = true